#304153690930924
#4bf89c1c5e2be6230bb4d8d8818c837c
server:
   port: 9090

security:
   oauth2:
     client:
        clientId: 304153690930924
        clientsecretId: 4bf89c1c5e2be6230bb4d8d8818c837c
        accessTokenUri: https://graph.facebook.com/oauth/access_token
        userAuthorizationUri: https://www.facebook.com/dialog/oauth
        tokenName: oauth_token
        authenticationScheme: query
        clientAuthenticationScheme: form
     resource:
        userInfoUri: https://graph.facebook.com/me